[package]
name = "sensorboost"
version = "0.1.0"
authors = ["Johnny Sloboda <sloboda@perpetualabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
