[package]
name = "brickgame"
version = "0.1.0"
authors = ["jsloboda <John Sloboda <sloboda@gmail.com>>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch = "0.2.1"
